import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import '../../App.css';
import Star1 from '../../assets/images/yulduz1.svg';
import Star2 from '../../assets/images/yulduz2.svg';
import heroBg from '../../assets/images/Bg.png';
import Animate from '../Animation/Animation';
export const Hero = () => {
    return (_jsxs("div", { className: 'mb-[72px]', children: [_jsxs("div", { className: 'bgHero py-[116px] relative', children: [_jsx("div", { className: 'container mx-auto flex justify-between items-center', children: _jsxs("div", { className: 'mb-[48px]', children: [_jsx("h1", { className: 'heroH1 w-[577px] font-[700] text-[64px] mb-[32px] leading-[64px]', children: "FIND CLOTHES THAT MATCHES YOUR STYLE" }), _jsx("p", { className: 'heroP w-[545px] font-[400] text-[16px] leading-[22px] mb-[32px]', children: "Browse through our diverse range of meticulously crafted garments, designed to bring out your individuality and cater to your sense of style." }), _jsx("button", { className: 'font-[500] text-[16px] border-[1px] border-black leading-[21.6px] text-white bg-black px-[67.5px] py-[15px] rounded-[62px] hover:bg-white hover:text-[black] duration-300 mb-[48px]', children: "Shop Now" }), _jsx("div", { children: _jsxs("ul", { className: 'flex flex-wrap justify-center numbers', children: [_jsxs("li", { className: 'border-r-[1px] border-[#00000033] pr-[32px]', children: [_jsx("p", { className: 'font-[700] text-[40px] leading-[54px]', children: "200+" }), _jsx("p", { className: 'font-[400] text-[16px] leading-[22px] text-[#00000099]', children: "International Brands" })] }), _jsxs("li", { className: 'numberCenter border-r-[1px] border-[#00000033] pl-[32px] pr-[32px]', children: [_jsx("p", { className: 'font-[700] text-[40px] leading-[54px]', children: "2,000+" }), _jsx("p", { className: 'font-[400] text-[16px] leading-[22px] text-[#00000099]', children: "High-Quality Products" })] }), _jsxs("li", { className: 'pl-[32px]', children: [_jsx("p", { className: 'font-[700] text-[40px] leading-[54px]', children: "30,000+" }), _jsx("p", { className: 'font-[400] text-[16px] leading-[22px] text-[#00000099]', children: "Happy Customers" })] })] }) })] }) }), _jsx("img", { className: 'star1 absolute top-[86px] right-[100px]', src: Star1, alt: "" }), _jsx("img", { className: 'star2 absolute top-[300px] right-[800px]', src: Star2, alt: "" }), _jsx("img", { className: 'Bg_img w-full h-full', src: heroBg, alt: "" })] }), _jsx(Animate, {})] }));
};
