import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import img1 from "../../assets/images/men1.png";
import img2 from "../../assets/images/men2.png";
import img3 from "../../assets/images/men3.png";
import img4 from "../../assets/images/men4.png";
const Dress = () => {
    return (_jsx("section", { children: _jsx("div", { className: "container mx-auto max-w-[1280px]", children: _jsxs("div", { className: "bg-[#F0F0F0] px-3 pb-4 pt-8 min-[550px]:px-5 lg:px-10 lg:pb-16 lg:pt-12 xl:px-14 rounded-xl", children: [_jsx("h2", { className: "text-3xl text-center lg:text-5xl font-bold mb-5", children: "BROWSE BY DRESS STYLE" }), _jsxs("div", { className: "grid grid-cols-1 gap-y-5 min-[800px]:grid-cols-3 min-[800px]:gap-x-3 lg:gap-y-7 lg:gap-x-7", children: [_jsxs("div", { className: "relative w-full rounded-xl xl:h-80 bg-white", children: [_jsx("img", { className: "w-full h-full object-cover rounded-xl hover:scale-105 transition-all", src: img1, alt: "" }), _jsx("p", { className: "text-2xl font-bold absolute top-[16px] left-[24px]", children: "Casual" })] }), _jsxs("div", { className: "relative rounded-xl xl:h-80 bg-white col-span-2 hover:scale-105 transition-all", children: [_jsx("img", { className: "ml-auto w-10/12 h-full rounded-xl", src: img2, alt: "" }), _jsx("p", { className: "text-2xl font-bold absolute top-[16px] left-[24px]", children: "Formal" })] }), _jsxs("div", { className: "relative rounded-xl xl:h-80 bg-white col-span-2 hover:scale-105 transition-all", children: [_jsx("img", { className: "ml-auto w-10/12 h-full rounded-xl", src: img3, alt: "" }), _jsx("p", { className: "text-2xl font-bold absolute top-[16px] left-[24px]", children: "Party" })] }), _jsxs("div", { className: "relative w-full rounded-xl xl:h-80 bg-white hover:scale-105 transition-all", children: [_jsx("img", { className: "w-full h-full object-cover rounded-xl", src: img4, alt: "" }), _jsx("p", { className: "text-2xl font-bold absolute top-[16px] left-[24px]", children: "Gym" })] })] })] }) }) }));
};
export default Dress;
